
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::GTKSharpTest.DLL.Widgets.FontDialogOfficeWidget fontdialogofficewidget1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fontdialogofficewidget1 = new global::GTKSharpTest.DLL.Widgets.FontDialogOfficeWidget ();
		this.fontdialogofficewidget1.Events = ((global::Gdk.EventMask)(256));
		this.fontdialogofficewidget1.Name = "fontdialogofficewidget1";
		this.Add (this.fontdialogofficewidget1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 728;
		this.DefaultHeight = 510;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
