
// This file has been generated by the GUI designer. Do not modify.
namespace GTKSharpTest.DLL.Widgets
{
	public partial class WindowColorPickerOfficeLike
	{
		private global::GTKSharpTest.DLL.Widgets.WidgetColorPickerOfficeLike widgetcolorpickerofficelike2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GTKSharpTest.DLL.Widgets.WindowColorPickerOfficeLike
			this.Name = "GTKSharpTest.DLL.Widgets.WindowColorPickerOfficeLike";
			this.Title = global::Mono.Unix.Catalog.GetString ("WindowColorPickerOfficeLike");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child GTKSharpTest.DLL.Widgets.WindowColorPickerOfficeLike.Gtk.Container+ContainerChild
			this.widgetcolorpickerofficelike2 = null;
			this.Add (this.widgetcolorpickerofficelike2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 534;
			this.DefaultHeight = 516;
			this.Show ();
		}
	}
}
