
// This file has been generated by the GUI designer. Do not modify.
namespace GTKSharpTest.DLL.Widgets
{
	public partial class FontDialogOfficeWidget
	{
		private global::Gtk.Notebook notebook1;
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label label3;
		private global::Gtk.Entry entryFont;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeviewFonts;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label label4;
		private global::Gtk.Entry entryFontStyle;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TreeView treeviewFontStyles;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label labelSize;
		private global::Gtk.Entry entryFontSize;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.TreeView treeviewFontSizes;
		private global::Gtk.HBox hbox2;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Label label5;
		private global::Gtk.Button buttonFontColor;
		private global::Gtk.VBox vbox6;
		private global::Gtk.Label label8;
		private global::Gtk.ComboBox comboboxUnderline;
		private global::Gtk.VBox vbox7;
		private global::Gtk.Label label9;
		private global::Gtk.Button buttonUndelineColor;
		private global::Gtk.VBox vbox8;
		private global::Gtk.Label label7;
		private global::Gtk.HBox hbox4;
		private global::Gtk.VBox vbox9;
		private global::Gtk.CheckButton checkbuttonStrikethrough;
		private global::Gtk.CheckButton checkbuttonDoubleStrikethrough;
		private global::Gtk.CheckButton checkbuttonSuperscript;
		private global::Gtk.CheckButton checkbuttonSubscript;
		private global::Gtk.VBox vbox10;
		private global::Gtk.CheckButton checkbuttonSmallCaps;
		private global::Gtk.CheckButton checkbuttonAllCaps;
		private global::Gtk.CheckButton checkbuttonHidden;
		private global::Gtk.ScrolledWindow GtkScrolledWindow3;
		private global::Gtk.TextView textviewDemoText;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Button buttonDefault;
		private global::Gtk.Button buttonTextEffects;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOK;
		private global::Gtk.Label label1;
		private global::Gtk.Label label2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GTKSharpTest.DLL.Widgets.FontDialogOfficeWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "GTKSharpTest.DLL.Widgets.FontDialogOfficeWidget";
			// Container child GTKSharpTest.DLL.Widgets.FontDialogOfficeWidget.Gtk.Container+ContainerChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			this.notebook1.BorderWidth = ((uint)(18));
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Font:");
			this.vbox2.Add (this.label3);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label3]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.entryFont = new global::Gtk.Entry ();
			this.entryFont.CanFocus = true;
			this.entryFont.Name = "entryFont";
			this.entryFont.IsEditable = true;
			this.entryFont.InvisibleChar = '●';
			this.vbox2.Add (this.entryFont);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.entryFont]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeviewFonts = new global::Gtk.TreeView ();
			this.treeviewFonts.CanFocus = true;
			this.treeviewFonts.Name = "treeviewFonts";
			this.GtkScrolledWindow.Add (this.treeviewFonts);
			this.vbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
			w4.Position = 2;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
			w5.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Font Style:");
			this.vbox3.Add (this.label4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label4]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.entryFontStyle = new global::Gtk.Entry ();
			this.entryFontStyle.CanFocus = true;
			this.entryFontStyle.Name = "entryFontStyle";
			this.entryFontStyle.IsEditable = true;
			this.entryFontStyle.InvisibleChar = '●';
			this.vbox3.Add (this.entryFontStyle);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.entryFontStyle]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeviewFontStyles = new global::Gtk.TreeView ();
			this.treeviewFontStyles.CanFocus = true;
			this.treeviewFontStyles.Name = "treeviewFontStyles";
			this.GtkScrolledWindow1.Add (this.treeviewFontStyles);
			this.vbox3.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow1]));
			w9.Position = 2;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w10.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.labelSize = new global::Gtk.Label ();
			this.labelSize.Name = "labelSize";
			this.labelSize.LabelProp = global::Mono.Unix.Catalog.GetString ("Size:");
			this.vbox4.Add (this.labelSize);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.labelSize]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.entryFontSize = new global::Gtk.Entry ();
			this.entryFontSize.CanFocus = true;
			this.entryFontSize.Name = "entryFontSize";
			this.entryFontSize.IsEditable = true;
			this.entryFontSize.InvisibleChar = '●';
			this.vbox4.Add (this.entryFontSize);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.entryFontSize]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.treeviewFontSizes = new global::Gtk.TreeView ();
			this.treeviewFontSizes.CanFocus = true;
			this.treeviewFontSizes.Name = "treeviewFontSizes";
			this.GtkScrolledWindow2.Add (this.treeviewFontSizes);
			this.vbox4.Add (this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow2]));
			w14.Position = 2;
			this.hbox1.Add (this.vbox4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox4]));
			w15.Position = 2;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Padding = ((uint)(5));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Homogeneous = true;
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Font color:");
			this.vbox5.Add (this.label5);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label5]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.buttonFontColor = new global::Gtk.Button ();
			this.buttonFontColor.CanFocus = true;
			this.buttonFontColor.Name = "buttonFontColor";
			this.buttonFontColor.UseUnderline = true;
			this.buttonFontColor.Label = global::Mono.Unix.Catalog.GetString ("Font Color");
			this.vbox5.Add (this.buttonFontColor);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.buttonFontColor]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.hbox2.Add (this.vbox5);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox5]));
			w19.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Underline style:");
			this.vbox6.Add (this.label8);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label8]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.comboboxUnderline = global::Gtk.ComboBox.NewText ();
			this.comboboxUnderline.AppendText (global::Mono.Unix.Catalog.GetString ("None"));
			this.comboboxUnderline.AppendText (global::Mono.Unix.Catalog.GetString ("Single"));
			this.comboboxUnderline.AppendText (global::Mono.Unix.Catalog.GetString ("Double"));
			this.comboboxUnderline.AppendText (global::Mono.Unix.Catalog.GetString ("Low"));
			this.comboboxUnderline.AppendText (global::Mono.Unix.Catalog.GetString ("Error"));
			this.comboboxUnderline.AppendText ("");
			this.comboboxUnderline.Name = "comboboxUnderline";
			this.vbox6.Add (this.comboboxUnderline);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.comboboxUnderline]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			this.hbox2.Add (this.vbox6);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox6]));
			w22.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Underline color:");
			this.vbox7.Add (this.label9);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.label9]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.buttonUndelineColor = new global::Gtk.Button ();
			this.buttonUndelineColor.CanFocus = true;
			this.buttonUndelineColor.Name = "buttonUndelineColor";
			this.buttonUndelineColor.UseUnderline = true;
			this.buttonUndelineColor.Label = global::Mono.Unix.Catalog.GetString ("Underline Color");
			this.vbox7.Add (this.buttonUndelineColor);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.buttonUndelineColor]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			this.hbox2.Add (this.vbox7);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox7]));
			w25.Position = 2;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Padding = ((uint)(5));
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Effects");
			this.vbox8.Add (this.label7);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.label7]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Homogeneous = true;
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.checkbuttonStrikethrough = new global::Gtk.CheckButton ();
			this.checkbuttonStrikethrough.CanFocus = true;
			this.checkbuttonStrikethrough.Name = "checkbuttonStrikethrough";
			this.checkbuttonStrikethrough.Label = global::Mono.Unix.Catalog.GetString ("Strikethrough");
			this.checkbuttonStrikethrough.DrawIndicator = true;
			this.checkbuttonStrikethrough.UseUnderline = true;
			this.vbox9.Add (this.checkbuttonStrikethrough);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.checkbuttonStrikethrough]));
			w28.Position = 0;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.checkbuttonDoubleStrikethrough = new global::Gtk.CheckButton ();
			this.checkbuttonDoubleStrikethrough.CanFocus = true;
			this.checkbuttonDoubleStrikethrough.Name = "checkbuttonDoubleStrikethrough";
			this.checkbuttonDoubleStrikethrough.Label = global::Mono.Unix.Catalog.GetString ("Double Strikethrough");
			this.checkbuttonDoubleStrikethrough.DrawIndicator = true;
			this.checkbuttonDoubleStrikethrough.UseUnderline = true;
			this.vbox9.Add (this.checkbuttonDoubleStrikethrough);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.checkbuttonDoubleStrikethrough]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.checkbuttonSuperscript = new global::Gtk.CheckButton ();
			this.checkbuttonSuperscript.CanFocus = true;
			this.checkbuttonSuperscript.Name = "checkbuttonSuperscript";
			this.checkbuttonSuperscript.Label = global::Mono.Unix.Catalog.GetString ("Superscript");
			this.checkbuttonSuperscript.DrawIndicator = true;
			this.checkbuttonSuperscript.UseUnderline = true;
			this.vbox9.Add (this.checkbuttonSuperscript);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.checkbuttonSuperscript]));
			w30.Position = 2;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.checkbuttonSubscript = new global::Gtk.CheckButton ();
			this.checkbuttonSubscript.CanFocus = true;
			this.checkbuttonSubscript.Name = "checkbuttonSubscript";
			this.checkbuttonSubscript.Label = global::Mono.Unix.Catalog.GetString ("Subscript");
			this.checkbuttonSubscript.DrawIndicator = true;
			this.checkbuttonSubscript.UseUnderline = true;
			this.vbox9.Add (this.checkbuttonSubscript);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.checkbuttonSubscript]));
			w31.Position = 3;
			w31.Expand = false;
			w31.Fill = false;
			this.hbox4.Add (this.vbox9);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox9]));
			w32.Position = 0;
			w32.Padding = ((uint)(30));
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.checkbuttonSmallCaps = new global::Gtk.CheckButton ();
			this.checkbuttonSmallCaps.CanFocus = true;
			this.checkbuttonSmallCaps.Name = "checkbuttonSmallCaps";
			this.checkbuttonSmallCaps.Label = global::Mono.Unix.Catalog.GetString ("Small caps");
			this.checkbuttonSmallCaps.DrawIndicator = true;
			this.checkbuttonSmallCaps.UseUnderline = true;
			this.vbox10.Add (this.checkbuttonSmallCaps);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.checkbuttonSmallCaps]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.checkbuttonAllCaps = new global::Gtk.CheckButton ();
			this.checkbuttonAllCaps.CanFocus = true;
			this.checkbuttonAllCaps.Name = "checkbuttonAllCaps";
			this.checkbuttonAllCaps.Label = global::Mono.Unix.Catalog.GetString ("All caps");
			this.checkbuttonAllCaps.DrawIndicator = true;
			this.checkbuttonAllCaps.UseUnderline = true;
			this.vbox10.Add (this.checkbuttonAllCaps);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.checkbuttonAllCaps]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.checkbuttonHidden = new global::Gtk.CheckButton ();
			this.checkbuttonHidden.CanFocus = true;
			this.checkbuttonHidden.Name = "checkbuttonHidden";
			this.checkbuttonHidden.Label = global::Mono.Unix.Catalog.GetString ("Hidden");
			this.checkbuttonHidden.DrawIndicator = true;
			this.checkbuttonHidden.UseUnderline = true;
			this.vbox10.Add (this.checkbuttonHidden);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.checkbuttonHidden]));
			w35.Position = 2;
			w35.Expand = false;
			w35.Fill = false;
			this.hbox4.Add (this.vbox10);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox10]));
			w36.Position = 1;
			w36.Padding = ((uint)(30));
			this.vbox8.Add (this.hbox4);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox4]));
			w37.Position = 1;
			w37.Expand = false;
			w37.Fill = false;
			this.vbox1.Add (this.vbox8);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox8]));
			w38.Position = 2;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.textviewDemoText = new global::Gtk.TextView ();
			this.textviewDemoText.Buffer.Text = "\n\nPlease\n\n";
			this.textviewDemoText.CanFocus = true;
			this.textviewDemoText.Name = "textviewDemoText";
			this.textviewDemoText.Justification = ((global::Gtk.Justification)(2));
			this.GtkScrolledWindow3.Add (this.textviewDemoText);
			this.vbox1.Add (this.GtkScrolledWindow3);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow3]));
			w40.Position = 3;
			w40.Padding = ((uint)(10));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Homogeneous = true;
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.buttonDefault = new global::Gtk.Button ();
			this.buttonDefault.WidthRequest = 120;
			this.buttonDefault.CanFocus = true;
			this.buttonDefault.Name = "buttonDefault";
			this.buttonDefault.UseUnderline = true;
			this.buttonDefault.Label = global::Mono.Unix.Catalog.GetString ("Default...");
			this.hbox3.Add (this.buttonDefault);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.buttonDefault]));
			w41.Position = 0;
			w41.Expand = false;
			w41.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.buttonTextEffects = new global::Gtk.Button ();
			this.buttonTextEffects.WidthRequest = 120;
			this.buttonTextEffects.CanFocus = true;
			this.buttonTextEffects.Name = "buttonTextEffects";
			this.buttonTextEffects.UseUnderline = true;
			this.buttonTextEffects.Label = global::Mono.Unix.Catalog.GetString ("Text Effect ...");
			this.hbox3.Add (this.buttonTextEffects);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.buttonTextEffects]));
			w42.Position = 1;
			w42.Expand = false;
			w42.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.WidthRequest = 120;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString ("Cancel");
			this.hbox3.Add (this.buttonCancel);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.buttonCancel]));
			w43.Position = 3;
			w43.Expand = false;
			w43.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.buttonOK = new global::Gtk.Button ();
			this.buttonOK.WidthRequest = 120;
			this.buttonOK.CanFocus = true;
			this.buttonOK.Name = "buttonOK";
			this.buttonOK.UseUnderline = true;
			this.buttonOK.Label = global::Mono.Unix.Catalog.GetString ("OK");
			this.hbox3.Add (this.buttonOK);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.buttonOK]));
			w44.Position = 4;
			w44.Expand = false;
			w44.Fill = false;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w45.PackType = ((global::Gtk.PackType)(1));
			w45.Position = 4;
			w45.Expand = false;
			w45.Fill = false;
			this.notebook1.Add (this.vbox1);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Font");
			this.notebook1.SetTabLabel (this.vbox1, this.label1);
			this.label1.ShowAll ();
			// Notebook tab
			global::Gtk.Label w47 = new global::Gtk.Label ();
			w47.Visible = true;
			this.notebook1.Add (w47);
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Advanced");
			this.notebook1.SetTabLabel (w47, this.label2);
			this.label2.ShowAll ();
			this.Add (this.notebook1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonFontColor.Clicked += new global::System.EventHandler (this.OnButtonFontColorClicked);
			this.comboboxUnderline.Changed += new global::System.EventHandler (this.OnComboboxUnderlineChanged);
			this.buttonUndelineColor.Clicked += new global::System.EventHandler (this.OnButtonUndelineColorClicked);
			this.checkbuttonStrikethrough.Toggled += new global::System.EventHandler (this.OnCheckbuttonStrikethroughToggled);
			this.checkbuttonDoubleStrikethrough.Toggled += new global::System.EventHandler (this.OnCheckbuttonDoubleStrikethroughToggled);
			this.checkbuttonSuperscript.Toggled += new global::System.EventHandler (this.OnCheckbuttonSuperscriptToggled);
			this.checkbuttonSubscript.Toggled += new global::System.EventHandler (this.OnCheckbuttonSubscriptToggled);
			this.checkbuttonSmallCaps.Toggled += new global::System.EventHandler (this.OnCheckbuttonSmallCapsToggled);
			this.checkbuttonAllCaps.Toggled += new global::System.EventHandler (this.OnCheckbuttonAllCapsToggled);
			this.checkbuttonHidden.Toggled += new global::System.EventHandler (this.OnCheckbuttonHiddenToggled);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.buttonOK.Clicked += new global::System.EventHandler (this.OnButtonOKClicked);
		}
	}
}
