
// This file has been generated by the GUI designer. Do not modify.
namespace GTKSharpTest.DLL.Widgets
{
	public partial class ButtonColorWidget
	{
		private global::Gtk.HBox hbox1;
		private global::Gtk.DrawingArea drawingarea1;
		private global::Gtk.Label labelColor;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GTKSharpTest.DLL.Widgets.ButtonColorWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "GTKSharpTest.DLL.Widgets.ButtonColorWidget";
			// Container child GTKSharpTest.DLL.Widgets.ButtonColorWidget.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Homogeneous = true;
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.drawingarea1 = new global::Gtk.DrawingArea ();
			this.drawingarea1.WidthRequest = 50;
			this.drawingarea1.Name = "drawingarea1";
			this.hbox1.Add (this.drawingarea1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.drawingarea1]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.labelColor = new global::Gtk.Label ();
			this.labelColor.Name = "labelColor";
			this.labelColor.LabelProp = global::Mono.Unix.Catalog.GetString ("Color");
			this.hbox1.Add (this.labelColor);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.labelColor]));
			w2.Position = 1;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
