
// This file has been generated by the GUI designer. Do not modify.
namespace GTKSharpTest.DLL.Widgets
{
	public partial class ListViewWidget
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GTKSharpTest.DLL.Widgets.ListViewWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "GTKSharpTest.DLL.Widgets.ListViewWidget";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
