
// This file has been generated by the GUI designer. Do not modify.
namespace GTKSharpTest.DLL.Widgets
{
	public partial class WidgetColorPickerOfficeLike
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label label3;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Image image11;
		private global::Gtk.Image image12;
		private global::Gtk.Image image13;
		private global::Gtk.Image image14;
		private global::Gtk.Image image15;
		private global::Gtk.Image image16;
		private global::Gtk.Image image17;
		private global::Gtk.Image image18;
		private global::Gtk.Image image19;
		private global::Gtk.Image image20;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.Table table1;
		private global::Gtk.Image image21;
		private global::Gtk.Image image24;
		private global::Gtk.Image image25;
		private global::Gtk.Image image26;
		private global::Gtk.Image image27;
		private global::Gtk.Image image28;
		private global::Gtk.Image image29;
		private global::Gtk.Image image30;
		private global::Gtk.Image image31;
		private global::Gtk.Image image32;
		private global::Gtk.Image image33;
		private global::Gtk.Image image34;
		private global::Gtk.Image image35;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Image image23;
		private global::Gtk.Label label6;
		private global::Gtk.Table table2;
		private global::Gtk.Image image22;
		private global::Gtk.Label label5;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GTKSharpTest.DLL.Widgets.WidgetColorPickerOfficeLike
			global::Stetic.BinContainer.Attach (this);
			this.Name = "GTKSharpTest.DLL.Widgets.WidgetColorPickerOfficeLike";
			// Container child GTKSharpTest.DLL.Widgets.WidgetColorPickerOfficeLike.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Theme Colors");
			this.vbox3.Add (this.label3);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label3]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.image11 = new global::Gtk.Image ();
			this.image11.Name = "image11";
			this.hbox2.Add (this.image11);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.image11]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.image12 = new global::Gtk.Image ();
			this.image12.Name = "image12";
			this.hbox2.Add (this.image12);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.image12]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.image13 = new global::Gtk.Image ();
			this.image13.Name = "image13";
			this.hbox2.Add (this.image13);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.image13]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.image14 = new global::Gtk.Image ();
			this.image14.Name = "image14";
			this.hbox2.Add (this.image14);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.image14]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.image15 = new global::Gtk.Image ();
			this.image15.Name = "image15";
			this.hbox2.Add (this.image15);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.image15]));
			w6.Position = 4;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.image16 = new global::Gtk.Image ();
			this.image16.Name = "image16";
			this.hbox2.Add (this.image16);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.image16]));
			w7.Position = 5;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.image17 = new global::Gtk.Image ();
			this.image17.Name = "image17";
			this.hbox2.Add (this.image17);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.image17]));
			w8.Position = 6;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.image18 = new global::Gtk.Image ();
			this.image18.Name = "image18";
			this.hbox2.Add (this.image18);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.image18]));
			w9.Position = 7;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.image19 = new global::Gtk.Image ();
			this.image19.Name = "image19";
			this.hbox2.Add (this.image19);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.image19]));
			w10.Position = 8;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.image20 = new global::Gtk.Image ();
			this.image20.Name = "image20";
			this.hbox2.Add (this.image20);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.image20]));
			w11.Position = 9;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox3.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator1]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(10)), ((uint)(10)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.image21 = new global::Gtk.Image ();
			this.image21.Name = "image21";
			this.table1.Add (this.image21);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.image21]));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.image24 = new global::Gtk.Image ();
			this.image24.Name = "image24";
			this.table1.Add (this.image24);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.image24]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.image25 = new global::Gtk.Image ();
			this.image25.Name = "image25";
			this.table1.Add (this.image25);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.image25]));
			w16.TopAttach = ((uint)(2));
			w16.BottomAttach = ((uint)(3));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.image26 = new global::Gtk.Image ();
			this.image26.Name = "image26";
			this.table1.Add (this.image26);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.image26]));
			w17.TopAttach = ((uint)(3));
			w17.BottomAttach = ((uint)(4));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.image27 = new global::Gtk.Image ();
			this.image27.Name = "image27";
			this.table1.Add (this.image27);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1 [this.image27]));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.image28 = new global::Gtk.Image ();
			this.image28.Name = "image28";
			this.table1.Add (this.image28);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1 [this.image28]));
			w19.LeftAttach = ((uint)(2));
			w19.RightAttach = ((uint)(3));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.image29 = new global::Gtk.Image ();
			this.image29.Name = "image29";
			this.table1.Add (this.image29);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1 [this.image29]));
			w20.LeftAttach = ((uint)(3));
			w20.RightAttach = ((uint)(4));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.image30 = new global::Gtk.Image ();
			this.image30.Name = "image30";
			this.table1.Add (this.image30);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1 [this.image30]));
			w21.LeftAttach = ((uint)(4));
			w21.RightAttach = ((uint)(5));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.image31 = new global::Gtk.Image ();
			this.image31.Name = "image31";
			this.table1.Add (this.image31);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1 [this.image31]));
			w22.LeftAttach = ((uint)(5));
			w22.RightAttach = ((uint)(6));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.image32 = new global::Gtk.Image ();
			this.image32.Name = "image32";
			this.table1.Add (this.image32);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1 [this.image32]));
			w23.LeftAttach = ((uint)(6));
			w23.RightAttach = ((uint)(7));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.image33 = new global::Gtk.Image ();
			this.image33.Name = "image33";
			this.table1.Add (this.image33);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1 [this.image33]));
			w24.LeftAttach = ((uint)(7));
			w24.RightAttach = ((uint)(8));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.image34 = new global::Gtk.Image ();
			this.image34.Name = "image34";
			this.table1.Add (this.image34);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1 [this.image34]));
			w25.LeftAttach = ((uint)(8));
			w25.RightAttach = ((uint)(9));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.image35 = new global::Gtk.Image ();
			this.image35.Name = "image35";
			this.table1.Add (this.image35);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1 [this.image35]));
			w26.LeftAttach = ((uint)(9));
			w26.RightAttach = ((uint)(10));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox3.Add (this.table1);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.table1]));
			w27.Position = 3;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.image23 = new global::Gtk.Image ();
			this.image23.Name = "image23";
			this.hbox3.Add (this.image23);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.image23]));
			w28.Position = 0;
			w28.Expand = false;
			w28.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("More Colors");
			this.hbox3.Add (this.label6);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label6]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
			w30.PackType = ((global::Gtk.PackType)(1));
			w30.Position = 4;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table (((uint)(1)), ((uint)(10)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.image22 = new global::Gtk.Image ();
			this.image22.Name = "image22";
			this.table2.Add (this.image22);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table2 [this.image22]));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox3.Add (this.table2);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.table2]));
			w32.PackType = ((global::Gtk.PackType)(1));
			w32.Position = 5;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Standard Colors");
			this.vbox3.Add (this.label5);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label5]));
			w33.PackType = ((global::Gtk.PackType)(1));
			w33.Position = 6;
			w33.Expand = false;
			w33.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
