
// This file has been generated by the GUI designer. Do not modify.
namespace HollyLibrary
{
	public partial class HImageCheckBox
	{
		private global::Gtk.EventBox ECheckbox;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Image ImgCheck;
		private global::HollyLibrary.HLabel LblText;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget HollyLibrary.HImageCheckBox
			global::Stetic.BinContainer.Attach (this);
			this.Name = "HollyLibrary.HImageCheckBox";
			// Container child HollyLibrary.HImageCheckBox.Gtk.Container+ContainerChild
			this.ECheckbox = new global::Gtk.EventBox ();
			this.ECheckbox.Events = ((global::Gdk.EventMask)(86004));
			this.ECheckbox.Name = "ECheckbox";
			// Container child ECheckbox.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			this.hbox1.BorderWidth = ((uint)(3));
			// Container child hbox1.Gtk.Box+BoxChild
			this.ImgCheck = new global::Gtk.Image ();
			this.ImgCheck.Name = "ImgCheck";
			this.hbox1.Add (this.ImgCheck);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.ImgCheck]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.LblText = null;
			this.hbox1.Add (this.LblText);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.LblText]));
			w2.Position = 1;
			this.ECheckbox.Add (this.hbox1);
			this.Add (this.ECheckbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
