
// This file has been generated by the GUI designer. Do not modify.
namespace HollyLibrary
{
	public partial class HColorPicker
	{
		private global::HollyLibrary.HBaseComboBox comboBox;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget HollyLibrary.HColorPicker
			global::Stetic.BinContainer.Attach (this);
			this.Name = "HollyLibrary.HColorPicker";
			// Container child HollyLibrary.HColorPicker.Gtk.Container+ContainerChild
			this.comboBox = null;
			this.Add (this.comboBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
