
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Table table1;
	private global::Gtk.Button buttonSubscribe;
	private global::Gtk.Button buttonUnsubscribe;
	private global::Gtk.ComboBoxEntry comboboxChannel;
	private global::Gtk.Label label10;
	private global::Gtk.Label label8;
	private global::Gtk.Label label9;
	private global::Gtk.Entry textBoxHostIPAddress;
	private global::Gtk.Entry textBoxPort;
	private global::Gtk.HBox hbox6;
	private global::Gtk.Label label12;
	private global::Gtk.Entry textBoxMessage;
	private global::Gtk.Button buttonNotify;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Label label11;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView textBoxMessages;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(6));
		this.AllowShrink = true;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(4)), true);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.buttonSubscribe = new global::Gtk.Button ();
		this.buttonSubscribe.CanFocus = true;
		this.buttonSubscribe.Name = "buttonSubscribe";
		this.buttonSubscribe.UseUnderline = true;
		this.buttonSubscribe.Label = global::Mono.Unix.Catalog.GetString ("Subscribe");
		this.table1.Add (this.buttonSubscribe);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonSubscribe]));
		w1.TopAttach = ((uint)(2));
		w1.BottomAttach = ((uint)(3));
		w1.LeftAttach = ((uint)(2));
		w1.RightAttach = ((uint)(3));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.buttonUnsubscribe = new global::Gtk.Button ();
		this.buttonUnsubscribe.CanFocus = true;
		this.buttonUnsubscribe.Name = "buttonUnsubscribe";
		this.buttonUnsubscribe.UseUnderline = true;
		this.buttonUnsubscribe.Label = global::Mono.Unix.Catalog.GetString ("Unsubscribe");
		this.table1.Add (this.buttonUnsubscribe);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonUnsubscribe]));
		w2.TopAttach = ((uint)(2));
		w2.BottomAttach = ((uint)(3));
		w2.LeftAttach = ((uint)(3));
		w2.RightAttach = ((uint)(4));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.comboboxChannel = global::Gtk.ComboBoxEntry.NewText ();
		this.comboboxChannel.Name = "comboboxChannel";
		this.table1.Add (this.comboboxChannel);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.comboboxChannel]));
		w3.TopAttach = ((uint)(2));
		w3.BottomAttach = ((uint)(3));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Channel:");
		this.table1.Add (this.label10);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.label10]));
		w4.TopAttach = ((uint)(2));
		w4.BottomAttach = ((uint)(3));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Host / IP addres:");
		this.table1.Add (this.label8);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.label8]));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Port:");
		this.table1.Add (this.label9);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.label9]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.textBoxHostIPAddress = new global::Gtk.Entry ();
		this.textBoxHostIPAddress.CanFocus = true;
		this.textBoxHostIPAddress.Name = "textBoxHostIPAddress";
		this.textBoxHostIPAddress.IsEditable = true;
		this.textBoxHostIPAddress.InvisibleChar = '●';
		this.table1.Add (this.textBoxHostIPAddress);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.textBoxHostIPAddress]));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.textBoxPort = new global::Gtk.Entry ();
		this.textBoxPort.CanFocus = true;
		this.textBoxPort.Name = "textBoxPort";
		this.textBoxPort.IsEditable = true;
		this.textBoxPort.InvisibleChar = '●';
		this.table1.Add (this.textBoxPort);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.textBoxPort]));
		w8.TopAttach = ((uint)(1));
		w8.BottomAttach = ((uint)(2));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.table1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Message:");
		this.hbox6.Add (this.label12);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label12]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.textBoxMessage = new global::Gtk.Entry ();
		this.textBoxMessage.CanFocus = true;
		this.textBoxMessage.Name = "textBoxMessage";
		this.textBoxMessage.IsEditable = true;
		this.textBoxMessage.InvisibleChar = '●';
		this.hbox6.Add (this.textBoxMessage);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.textBoxMessage]));
		w11.Position = 1;
		// Container child hbox6.Gtk.Box+BoxChild
		this.buttonNotify = new global::Gtk.Button ();
		this.buttonNotify.CanFocus = true;
		this.buttonNotify.Name = "buttonNotify";
		this.buttonNotify.UseUnderline = true;
		this.buttonNotify.Label = global::Mono.Unix.Catalog.GetString ("Notify");
		this.hbox6.Add (this.buttonNotify);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.buttonNotify]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.vbox1.Add (this.hbox6);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox6]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Messages:");
		this.hbox1.Add (this.label11);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label11]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textBoxMessages = new global::Gtk.TextView ();
		this.textBoxMessages.CanFocus = true;
		this.textBoxMessages.Name = "textBoxMessages";
		this.GtkScrolledWindow.Add (this.textBoxMessages);
		this.hbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.GtkScrolledWindow]));
		w16.Position = 1;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w17.Position = 2;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 774;
		this.DefaultHeight = 462;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
