
// This file has been generated by the GUI designer. Do not modify.
namespace HollyLibrary
{
	public partial class ComboListWindow
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::HollyLibrary.HSimpleList TvList;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget HollyLibrary.ComboListWindow
			this.Name = "HollyLibrary.ComboListWindow";
			this.Title = "ComboListWindow";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Decorated = false;
			// Container child HollyLibrary.ComboListWindow.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.TvList = null;
			this.GtkScrolledWindow.Add (this.TvList);
			this.Add (this.GtkScrolledWindow);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 264;
			this.DefaultHeight = 242;
			this.Show ();
			this.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnButtonPressEvent);
		}
	}
}
