
// This file has been generated by the GUI designer. Do not modify.
namespace HollyLibrary
{
	public partial class HToolTip
	{
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label Spacer;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label SpacerLeft;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Image ImgIcon;
		private global::Gtk.VBox vbox6;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label LblTitle;
		private global::Gtk.HSeparator hseparator2;
		private global::Gtk.Label LblContent;
		private global::Gtk.Label SpacerRight;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget HollyLibrary.HToolTip
			this.Name = "HollyLibrary.HToolTip";
			this.Title = "HToolTip";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Decorated = false;
			this.SkipPagerHint = true;
			this.SkipTaskbarHint = true;
			this.FocusOnMap = false;
			// Container child HollyLibrary.HToolTip.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.Spacer = new global::Gtk.Label ();
			this.Spacer.Name = "Spacer";
			this.vbox4.Add (this.Spacer);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.Spacer]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 2;
			this.hbox2.BorderWidth = ((uint)(8));
			// Container child hbox2.Gtk.Box+BoxChild
			this.SpacerLeft = new global::Gtk.Label ();
			this.SpacerLeft.Name = "SpacerLeft";
			this.hbox2.Add (this.SpacerLeft);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.SpacerLeft]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.ImgIcon = new global::Gtk.Image ();
			this.ImgIcon.Name = "ImgIcon";
			this.ImgIcon.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-info", global::Gtk.IconSize.Menu);
			this.vbox5.Add (this.ImgIcon);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.ImgIcon]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			this.hbox2.Add (this.vbox5);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox5]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 2;
			this.vbox6.BorderWidth = ((uint)(2));
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.LblTitle = new global::Gtk.Label ();
			this.LblTitle.Name = "LblTitle";
			this.LblTitle.Xalign = 0F;
			this.LblTitle.Yalign = 0F;
			this.LblTitle.LabelProp = "<b>title</b>";
			this.LblTitle.UseMarkup = true;
			this.hbox3.Add (this.LblTitle);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.LblTitle]));
			w5.Position = 0;
			this.vbox6.Add (this.hbox3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox3]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vbox6.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hseparator2]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.LblContent = new global::Gtk.Label ();
			this.LblContent.Name = "LblContent";
			this.LblContent.Xalign = 0F;
			this.LblContent.Yalign = 0F;
			this.LblContent.LabelProp = "    * HFontPicker - a office like font picker widget\n    * HDateEdit - a date-tim" +
			"e picker supporting custom formatting options\n    * HColorPicker - a simple colo" +
			"r picker drop-down ( office like ) \n\n";
			this.LblContent.Wrap = true;
			this.vbox6.Add (this.LblContent);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.LblContent]));
			w8.Position = 2;
			this.hbox2.Add (this.vbox6);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox6]));
			w9.Position = 2;
			// Container child hbox2.Gtk.Box+BoxChild
			this.SpacerRight = new global::Gtk.Label ();
			this.SpacerRight.Name = "SpacerRight";
			this.hbox2.Add (this.SpacerRight);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.SpacerRight]));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox4.Add (this.hbox2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox2]));
			w11.Position = 1;
			this.Add (this.vbox4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 424;
			this.DefaultHeight = 215;
			this.Hide ();
			this.SizeAllocated += new global::Gtk.SizeAllocatedHandler (this.OnSizeAllocated);
		}
	}
}
