
// This file has been generated by the GUI designer. Do not modify.
namespace HollyLibrary
{
	public partial class ColorPickerDialog
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Table TblColors;
		private global::Gtk.Button BtnMoreColors;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget HollyLibrary.ColorPickerDialog
			this.Name = "HollyLibrary.ColorPickerDialog";
			this.Title = "ColorPickerDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			this.Decorated = false;
			this.DestroyWithParent = true;
			this.SkipPagerHint = true;
			this.SkipTaskbarHint = true;
			// Container child HollyLibrary.ColorPickerDialog.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(5));
			// Container child vbox1.Gtk.Box+BoxChild
			this.TblColors = new global::Gtk.Table (((uint)(5)), ((uint)(8)), true);
			this.TblColors.Name = "TblColors";
			this.TblColors.RowSpacing = ((uint)(1));
			this.TblColors.ColumnSpacing = ((uint)(1));
			this.vbox1.Add (this.TblColors);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.TblColors]));
			w1.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.BtnMoreColors = new global::Gtk.Button ();
			this.BtnMoreColors.CanFocus = true;
			this.BtnMoreColors.Name = "BtnMoreColors";
			this.BtnMoreColors.UseUnderline = true;
			this.BtnMoreColors.Label = "More";
			global::Gtk.Image w2 = new global::Gtk.Image ();
			w2.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-color-picker", global::Gtk.IconSize.Menu);
			this.BtnMoreColors.Image = w2;
			this.vbox1.Add (this.BtnMoreColors);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.BtnMoreColors]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 230;
			this.DefaultHeight = 160;
			this.Show ();
			this.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnButtonPressEvent);
			this.BtnMoreColors.Clicked += new global::System.EventHandler (this.OnBtnMoreColorsClicked);
		}
	}
}
